#!/bin/sh

set -e

if pidof openvpn > /dev/null; then
	echo Already running
	exit 1
fi

[ "`id -u`" = "0" ] || exec sudo /usr/local/bin/ovpn

cd /root/.vpn
mkdir -m 700 -p /run/ovpn/tmp
/usr/sbin/openvpn --daemon --config /root/.vpn/client.ovpn --ping-exit 3600 \
	--chroot /run/ovpn --user proxy --group proxy
echo "Waiting for VPN starting up..."

while ! /bin/ip route | /bin/grep -q ' via .* dev tun0 '; do
        if ! pidof openvpn > /dev/null; then
                echo "OpenVPN startup failed."
                exit 1
        fi
        sleep 0.3
done

echo "VPN is up."
/bin/ip route del 172.16.0.0/12 || /bin/ip route del 172.16.0.0/13
exit 0
