#!/bin/sh

/usr/bin/light-locker --lock-on-suspend&
/usr/bin/xmodmap - <<KEYMAP
clear lock
keycode 66 = dead_diaeresis dead_tilde bar
keycode 96 = Next
keycode 107 = Prior
KEYMAP
/usr/bin/xset dpms SLEEP_SEC
mkdir -m 700 -p /tmp/.USERNAME-cache
redshift -oP >/dev/null 2>&1
#picom -b --backend glx --vsync
