PATH="$HOME/bin:$PATH:$HOME/.opam/default/bin"
[ -z "$PS1" ] && return
PS1='\h \w\[\e`[ $? = 0 ]&&echo \e[32m||echo \e[31m`\]/\[\e[0m\] '
if [ -x /usr/bin/nvim ]; then export MANPAGER='/usr/bin/nvim +Man!'
elif [ -x /usr/bin/vim ]; then export MANPAGER="/usr/bin/vim +MANPAGER '+map q :quit<CR>' '+set linebreak' --not-a-term -"
fi
export JAVA_HOME=/usr/lib/jvm/default-java
alias less='less -c'
alias jgrep='rg -tjava'
alias bc='bc -l'
alias ocaml='rlwrap ocaml'
alias screen='env LOCKPRG=/bin/true screen'
alias sad='ssh-add'
alias ssh='TERM=xterm-256color ssh'
