[[protocols]]
name = "vestel_rc_4862"
protocol = "rc5"
variant = "rc5"
[protocols.scancodes]
0x0100 = "KEY_0"
0x0101 = "KEY_1"
0x0102 = "KEY_2"
0x0103 = "KEY_3"
0x0104 = "KEY_4"
0x0105 = "KEY_5"
0x0106 = "KEY_6"
0x0107 = "KEY_7"
0x0108 = "KEY_8"
0x0109 = "KEY_9"
0x010a = "KEY_BACK"
0x010b = "KEY_SWITCHVIDEOMODE"
0x010c = "KEY_POWER"
0x010d = "KEY_MUTE"
0x010f = "KEY_LANGUAGE"
0x0110 = "KEY_VOLUMEUP"
0x0112 = "KEY_INFO"
0x0111 = "KEY_VOLUMEDOWN"
0x0113 = "KEY_DOWN"
0x0114 = "KEY_UP"
0x0115 = "KEY_LEFT"
0x0116 = "KEY_RIGHT"
0x0118 = "KEY_STOP"
0x0119 = "KEY_PLAY"
0x011a = "KEY_MODE"
0x011b = "KEY_REWIND"
0x011c = "KEY_FASTFORWARD"
0x011f = "KEY_SUBTITLE"
0x0120 = "KEY_CHANNELUP"
0x0121 = "KEY_CHANNELDOWN"
0x0122 = "KEY_LAST"
0x0125 = "KEY_EXIT"
0x0126 = "KEY_TV"
0x012b = "KEY_OPTION"
0x012e = "KEY_WWW"
0x012f = "KEY_PROGRAM"
0x0130 = "KEY_MENU"
0x0131 = "KEY_PAUSE"
0x0132 = "KEY_YELLOW"
0x0133 = "KEY_RECORD"
0x0134 = "KEY_BLUE"
0x0135 = "KEY_OK"
0x0136 = "KEY_GREEN"
0x0137 = "KEY_RED"
0x0138 = "KEY_PC"
0x0139 = "KEY_MEDIA"
0x013b = "KEY_PLAYER"
0x013c = "KEY_TEXT"
