#!/bin/sh

set -e

if pidof openvpn > /dev/null; then
	if [ "`id -u`" = "0" ]; then
		/usr/bin/killall openvpn
	else
		echo Already running
		exit 1
	fi
fi

[ "`id -u`" = "0" ] || exec doas /usr/local/bin/ovpn

if ! [ -e /run/netns/vip ]; then
	ip netns add vip
	ip link add evp0 type veth peer name enp1s0
	ip link set enp1s0 netns vip
	ip addr add 192.168.0.1/30 dev evp0
	ip link set evp0 up

	ip netns exec vip sh <<VIP_NS
ip link set lo up
nft -f - <<VIP_NFT
flush ruleset
table ip nat {
	chain postrouting {
		type nat hook postrouting priority 100;
		masquerade
	}
}
VIP_NFT
ip addr add 192.168.0.2/24 dev enp1s0
ip link set enp1s0 up
ip route add default via 192.168.0.1 dev enp1s0
VIP_NS
	ip route add 192.168.0.0/16 via 192.168.0.2
fi

NETNS="ip netns exec vip"

cd /root/.vpn
mkdir -m 700 -p /run/ovpn/tmp
$NETNS /usr/sbin/openvpn --daemon --config /root/.vpn/client.ovpn --dev tun0vpn \
	--persist-key --persist-tun --chroot /run/ovpn --user proxy --group proxy \
	--pull-filter ignore dhcp-pre-release --pull-filter ignore dhcp-renew \
	--pull-filter ignore dhcp-release --pull-filter ignore register-dns
echo "Waiting for VPN starting up..."

while ! $NETNS ip route | /bin/grep -q ' via .* dev tun0vpn '; do
        if ! pidof openvpn > /dev/null; then
                echo "OpenVPN startup failed."
                exit 1
        fi
        sleep 0.3
done

echo "VPN is up."
